### ISSUE TITLE
MIDI Not Initialized - OBS v24

### ISSUE THREAD

**Issue by ItsShamed** [rednetio/chord-display#6]
MIDI Not Initialized when loading it from the Browser Source in OBS Studio 24.0.3 (+OBS.Live v 20.2.17.565) even if I entered the MIDI Device in the GET Attribute (through URL). _(Is web midi working?)_
![Capture](https://user-images.githubusercontent.com/39100084/75585006-6d503a00-5a71-11ea-983e-531f206ddda0.PNG)
![Capture2](https://user-images.githubusercontent.com/39100084/75585064-8bb63580-5a71-11ea-9116-074b57a71090.PNG)

**Comment by ArTiSTiX** [comment]
@CubicFace Happy to know you tried chord-display !

Yes, this is an issue i discovered recently, OBS v24 (particularly the Chromium Embedded version used by obs-browser) fails, due to an unknown issue, throwing a SecurityError.

Here is the issue https://github.com/obsproject/obs-browser/issues/195

I personally rolled back to OBS Studio v23, hoping the obs-browser team find a solution.

**Comment by ItsShamed** [comment]
Oh, ok, it's a little bit annoying for me since I have plugins installed on OBS and I don't know if those plugins will be compatible with v23. But I'll find a way to install both versions on the same machine.
Thanks anyways.

**Comment by ArTiSTiX** [comment]
@CubicFace Thanks !

Do not hesitate if you have time to check if OBS v23 on Windows works - obs-browser maintainer seems to say upgrade was done earlier on Windows version.

I keep the issue open, will close it once it's working on the latest OBS, i'm very sad MIDI broke on the latest version only a few days after i deployed it.

I will keep you upd-to-date !

Enjoy your FL session anyway ;)

**Comment by ItsShamed** [comment]
![image](https://user-images.githubusercontent.com/39100084/75586674-3da33100-5a75-11ea-8414-a5f137f1f060.png)
I don't know if it's beacause I installed OBS v23 on a different directory but it seems that it's not working either on a fresh version (v23.0.1)

**Comment by ArTiSTiX** [comment]
@CubicFace Thanks again for testing, i will investigate as soon as possible, i think the v23 on windows is not working either, and i am on MacOS so i currently can't test it on a Windows environment.

**Comment by ArTiSTiX** [comment]
@ItsShamed Hello,

Sorry for the late feedback, i took some time (2 years ??) to think about the future of chord-display.
There are two problems that make chord-display unusable:
* MIDI drivers on Windows are exclusive, and after switching to Windows (i was a MacOS user when developing chord-display), i was no longer able to use chord-display AND FL Studio, both connected to the same keyboard.
* OBS Browser Source still does not support MIDI (even after waiting some issues to be solved in the Chromium Embedded Framework they use to allow it).

So i reworked it completely as a Standalone App made with Electron, that will allow me to develop many more features than *just* displaying chords and a keyboard.

You can find it here:
https://github.com/la-jarre-a-son/midi-jar

Chord display will not be maintained anymore, in favor of a more robust and complete solution with MIDI Jar.
(it was already too hard to maintain due to tonal being rewritten, and my UI being crap to integrate more customization).
